--------------------------------------------------------
-- Archivo creado  - viernes-abril-18-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLEADOR
--------------------------------------------------------

  CREATE TABLE "COSORIO"."EMPLEADOR" 
   (	"COD_EMPLEADOR" VARCHAR2(20 BYTE), 
	"RAZ_EMPLEADOR" VARCHAR2(500 BYTE), 
	"NOMCOM_EMPLEADOR" VARCHAR2(150 BYTE), 
	"DIR_EMPLEADOR" VARCHAR2(200 BYTE), 
	"REF_EMPLEADOR" VARCHAR2(80 BYTE), 
	"DIS_EMPLEADOR" VARCHAR2(30 BYTE), 
	"PRO_EMPLEADOR" VARCHAR2(30 BYTE), 
	"DEP_EMPLEADOR" VARCHAR2(30 BYTE), 
	"SEC_EMPLEADOR" VARCHAR2(12 BYTE), 
	"SEG_EMPLEADOR" VARCHAR2(21 BYTE), 
	"CON_EMPLEADOR" VARCHAR2(40 BYTE), 
	"EST_EMPLEADOR" VARCHAR2(40 BYTE), 
	"TEL_EMPLEADOR" VARCHAR2(80 BYTE), 
	"FECINS_EMPLEADOR" DATE, 
	"FECINI_EMPLEADOR" DATE, 
	"FEC_EMPLEADOR" DATE, 
	"TIP_EMPLEADOR" VARCHAR2(80 BYTE), 
	"REP_EMPLEADOR" VARCHAR2(100 BYTE), 
	"EMP_EMPLEADOR" VARCHAR2(100 BYTE), 
	"CARREP_EMPLEADOR" VARCHAR2(60 BYTE), 
	"CONEMP_EMPLEADOR" VARCHAR2(80 BYTE), 
	"TIPCON_EMPLEADOR" VARCHAR2(150 BYTE), 
	"OFI_EMPLEADOR" VARCHAR2(150 BYTE), 
	"SUBSECT_EMPLEADOR" VARCHAR2(30 BYTE), 
	"FAX_EMPLEADOR" VARCHAR2(200 BYTE), 
	"CIU_EMPLEADOR" VARCHAR2(200 BYTE), 
	"SECCIU1_EMPLEADOR" VARCHAR2(200 BYTE), 
	"SECCIU2_EMPLEADOR" VARCHAR2(200 BYTE), 
	"AFE_EMPLEADOR" VARCHAR2(200 BYTE), 
	"BUE_EMPLEADOR" VARCHAR2(200 BYTE), 
	"AGERET_EMPLEADOR" VARCHAR2(200 BYTE), 
	"AGEPER_EMPLEADOR" VARCHAR2(200 BYTE), 
	"AGEPERC_EMPLEADOR" VARCHAR2(200 BYTE), 
	"TIPODOC_EMPLEADOR" VARCHAR2(3 BYTE), 
	"RUC_SECTOR" VARCHAR2(30 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"REFAUX_EMPLEADOR" VARCHAR2(200 BYTE), 
	"REFAUX2_EMPLEADOR" VARCHAR2(200 CHAR), 
	"ESTREFER_EMPLEADOR" CHAR(1 BYTE), 
	"CODDEPEN_EMPLEADOR" VARCHAR2(4 BYTE), 
	"CODUBIG_EMPLEADOR" VARCHAR2(6 BYTE), 
	"TIPDOC_EMPLEADOR" VARCHAR2(2 CHAR), 
	"NUMDOC_EMPLEADOR" VARCHAR2(15 CHAR), 
	"CORREO_EMPLEADOR" VARCHAR2(70 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 33554432 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTAIND_DATA" ;

   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."COD_EMPLEADOR" IS 'Codigo unico de empleador  (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."RAZ_EMPLEADOR" IS 'Razon social del empleador (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."NOMCOM_EMPLEADOR" IS 'Nombre comercial (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."DIR_EMPLEADOR" IS 'Domicilio fiscal del empleado (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."REF_EMPLEADOR" IS 'Referencia de domicilio del empleador (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."DIS_EMPLEADOR" IS 'Distrito del empleador del empleador (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."PRO_EMPLEADOR" IS 'Provincia del empleador del empleador (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."DEP_EMPLEADOR" IS 'Departamento del empleador del empleado (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."SEC_EMPLEADOR" IS 'Sector del empleador';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."SEG_EMPLEADOR" IS 'Tipo de seguro del empleador';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."CON_EMPLEADOR" IS 'Condicion del empleador en sunat (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."EST_EMPLEADOR" IS 'Estado del empleador en sunat (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."TEL_EMPLEADOR" IS 'Telefono del empleador (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."FECINS_EMPLEADOR" IS 'Fecha de inscripcion (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."FECINI_EMPLEADOR" IS 'Fecha de inicio de actividades (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."FEC_EMPLEADOR" IS 'Fecha de registro o actualizacion de datos';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."TIP_EMPLEADOR" IS 'tipo de contribuyente (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."REP_EMPLEADOR" IS 'Representante de la empresa';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."EMP_EMPLEADOR" IS 'empleado de la empresa (con quien se comunico para notificacion telefonica)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."CARREP_EMPLEADOR" IS 'Cargo del representante de la empresa';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."CONEMP_EMPLEADOR" IS 'Observacion de contacto. Telefonos para contacto con el representante legal';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."TIPCON_EMPLEADOR" IS 'tipo de contribuyente (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."OFI_EMPLEADOR" IS 'profesion u oficio (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."SUBSECT_EMPLEADOR" IS 'sub sectro del empleador (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."FAX_EMPLEADOR" IS 'fax del empleador (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."CIU_EMPLEADOR" IS 'principal CIIU (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."SECCIU1_EMPLEADOR" IS 'secundario 1 CIIU
(se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."SECCIU2_EMPLEADOR" IS 'secundario 2 CIIU (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."AFE_EMPLEADOR" IS 'afecto nuevo RUS (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."BUE_EMPLEADOR" IS 'buen contribuyente (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."AGERET_EMPLEADOR" IS 'agente de retencion (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."AGEPER_EMPLEADOR" IS 'agente de percepcion vtaint (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."AGEPERC_EMPLEADOR" IS 'agente de percepcion comliq (se obtiene con consulta sunat)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."TIPODOC_EMPLEADOR" IS 'tipo de documento: ruc, dni';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."REFAUX_EMPLEADOR" IS 'Referencia de domicilio del empleador (registrado como segunda opcion)';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."REFAUX2_EMPLEADOR" IS 'Domiclio fiscal del empleador que sufrio alguna modificacion y se copia la direccion previa.';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."ESTREFER_EMPLEADOR" IS 'Estado de referencia de la direccion ';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."TIPDOC_EMPLEADOR" IS 'tipo de documento de identidad para RUC que inician con 10, 15 o 17';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."NUMDOC_EMPLEADOR" IS 'número de documento de identidad';
   COMMENT ON COLUMN "COSORIO"."EMPLEADOR"."CORREO_EMPLEADOR" IS 'correo del empleador';
  GRANT REFERENCES ON "COSORIO"."EMPLEADOR" TO PUBLIC;
  GRANT UPDATE ON "COSORIO"."EMPLEADOR" TO PUBLIC;
  GRANT SELECT ON "COSORIO"."EMPLEADOR" TO PUBLIC;
  GRANT INSERT ON "COSORIO"."EMPLEADOR" TO PUBLIC;
  GRANT INDEX ON "COSORIO"."EMPLEADOR" TO PUBLIC;
  GRANT DELETE ON "COSORIO"."EMPLEADOR" TO PUBLIC;
  GRANT ALTER ON "COSORIO"."EMPLEADOR" TO PUBLIC;
  
  REM INSERTING into COSORIO.EMPLEADOR
SET DEFINE OFF;
Insert into COSORIO.EMPLEADOR (COD_EMPLEADOR,RAZ_EMPLEADOR,NOMCOM_EMPLEADOR,DIR_EMPLEADOR,REF_EMPLEADOR,DIS_EMPLEADOR,PRO_EMPLEADOR,DEP_EMPLEADOR,SEC_EMPLEADOR,SEG_EMPLEADOR,CON_EMPLEADOR,EST_EMPLEADOR,TEL_EMPLEADOR,FECINS_EMPLEADOR,FECINI_EMPLEADOR,FEC_EMPLEADOR,TIP_EMPLEADOR,REP_EMPLEADOR,EMP_EMPLEADOR,CARREP_EMPLEADOR,CONEMP_EMPLEADOR,TIPCON_EMPLEADOR,OFI_EMPLEADOR,SUBSECT_EMPLEADOR,FAX_EMPLEADOR,CIU_EMPLEADOR,SECCIU1_EMPLEADOR,SECCIU2_EMPLEADOR,AFE_EMPLEADOR,BUE_EMPLEADOR,AGERET_EMPLEADOR,AGEPER_EMPLEADOR,AGEPERC_EMPLEADOR,TIPODOC_EMPLEADOR,RUC_SECTOR,FECHA_MODIFICACION,REFAUX_EMPLEADOR,REFAUX2_EMPLEADOR,ESTREFER_EMPLEADOR,CODDEPEN_EMPLEADOR,CODUBIG_EMPLEADOR,TIPDOC_EMPLEADOR,NUMDOC_EMPLEADOR,CORREO_EMPLEADOR) values ('10564283491','Castillo Morales Juan Carlos','CEP JESUS DIVINO MAESTRO','N° N^6 INT. 12 A.H. LOS ROSALES II ETAPA  ANCON - LIMA - LIMA','ALT KM 39 DE LA PAN NORTA - MZ ENNIE 6','ANCON','LIMA','LIMA','PRIVADO',null,'HABIDO','ACTIVO','- / - / -',to_date('13/11/1995','DD/MM/RRRR'),to_date('13/11/1995','DD/MM/RRRR'),to_date('27/04/2023','DD/MM/RRRR'),'PERSONA NATURAL CON NEGOCIO',null,null,null,null,'PERSONA NATURAL CON NEGOCIO','-',null,null,'ENSE%ANZA PRIMARIA',null,null,null,null,null,null,null,'RUC',null,to_date('06/06/2023','DD/MM/RRRR'),null,'N° N^6 INT. 12 A.H. LOS ROSALES II ETAPA  ANCON - LIMA - LIMA',null,'0023','150102','01','06128389       ',null);
Insert into COSORIO.EMPLEADOR (COD_EMPLEADOR,RAZ_EMPLEADOR,NOMCOM_EMPLEADOR,DIR_EMPLEADOR,REF_EMPLEADOR,DIS_EMPLEADOR,PRO_EMPLEADOR,DEP_EMPLEADOR,SEC_EMPLEADOR,SEG_EMPLEADOR,CON_EMPLEADOR,EST_EMPLEADOR,TEL_EMPLEADOR,FECINS_EMPLEADOR,FECINI_EMPLEADOR,FEC_EMPLEADOR,TIP_EMPLEADOR,REP_EMPLEADOR,EMP_EMPLEADOR,CARREP_EMPLEADOR,CONEMP_EMPLEADOR,TIPCON_EMPLEADOR,OFI_EMPLEADOR,SUBSECT_EMPLEADOR,FAX_EMPLEADOR,CIU_EMPLEADOR,SECCIU1_EMPLEADOR,SECCIU2_EMPLEADOR,AFE_EMPLEADOR,BUE_EMPLEADOR,AGERET_EMPLEADOR,AGEPER_EMPLEADOR,AGEPERC_EMPLEADOR,TIPODOC_EMPLEADOR,RUC_SECTOR,FECHA_MODIFICACION,REFAUX_EMPLEADOR,REFAUX2_EMPLEADOR,ESTREFER_EMPLEADOR,CODDEPEN_EMPLEADOR,CODUBIG_EMPLEADOR,TIPDOC_EMPLEADOR,NUMDOC_EMPLEADOR,CORREO_EMPLEADOR) values ('10163893465','Ramírez Ramírez Carla E.',null,'CAL. VON LEONARD N° 234 DPTO. 402 URB. CORPAC  SAN BORJA - LIMA - LIMA','-','SAN BORJA','LIMA','LIMA','PRIVADO',null,'HABIDO','ACTIVO','- / - / -',to_date('09/01/1998','DD/MM/RRRR'),to_date('09/01/1998','DD/MM/RRRR'),to_date('15/04/2015','DD/MM/RRRR'),'PERSONA NATURAL SIN NEGOCIO',null,null,null,null,'PERSONA NATURAL SIN NEGOCIO',null,null,null,'ACTIVIDADES JURIDICAS',null,null,null,null,null,null,null,'RUC',null,to_date('06/06/2023','DD/MM/RRRR'),null,'CAL. VON LEONARD N. 234   Dpto. 402   URB. CORPAC    SAN BORJA - LIMA - LIMA',null,'0023','150130',null,null,null);
Insert into COSORIO.EMPLEADOR (COD_EMPLEADOR,RAZ_EMPLEADOR,NOMCOM_EMPLEADOR,DIR_EMPLEADOR,REF_EMPLEADOR,DIS_EMPLEADOR,PRO_EMPLEADOR,DEP_EMPLEADOR,SEC_EMPLEADOR,SEG_EMPLEADOR,CON_EMPLEADOR,EST_EMPLEADOR,TEL_EMPLEADOR,FECINS_EMPLEADOR,FECINI_EMPLEADOR,FEC_EMPLEADOR,TIP_EMPLEADOR,REP_EMPLEADOR,EMP_EMPLEADOR,CARREP_EMPLEADOR,CONEMP_EMPLEADOR,TIPCON_EMPLEADOR,OFI_EMPLEADOR,SUBSECT_EMPLEADOR,FAX_EMPLEADOR,CIU_EMPLEADOR,SECCIU1_EMPLEADOR,SECCIU2_EMPLEADOR,AFE_EMPLEADOR,BUE_EMPLEADOR,AGERET_EMPLEADOR,AGEPER_EMPLEADOR,AGEPERC_EMPLEADOR,TIPODOC_EMPLEADOR,RUC_SECTOR,FECHA_MODIFICACION,REFAUX_EMPLEADOR,REFAUX2_EMPLEADOR,ESTREFER_EMPLEADOR,CODDEPEN_EMPLEADOR,CODUBIG_EMPLEADOR,TIPDOC_EMPLEADOR,NUMDOC_EMPLEADOR,CORREO_EMPLEADOR) values ('20121617624','Tienda Clásica S.A.C.','-','JR. AREQUIPA N° 163 CHOSICA  LURIGANCHO - LIMA - LIMA','-                                       ','LURIGANCHO','LIMA','LIMA','PRIVADO',null,'HABIDO','ACTIVO','- / - / -',to_date('09/03/1993','DD/MM/RRRR'),to_date('01/10/1975','DD/MM/RRRR'),to_date('04/05/2023','DD/MM/RRRR'),'SOCIEDAD ANONIMA CERRADA','TAYRAKO SAKAGUCHI GUILLERMO',null,'GERENTE',null,'SOCIEDAD ANONIMA CERRADA',null,null,null,'OTROS TIPOS DE VENTA AL POR MENOR.',null,null,null,null,null,null,null,'RUC',null,to_date('10/01/2024','DD/MM/RRRR'),null,'JR. AREQUIPA N° 163 CHOSICA  LURIGANCHO - LIMA - LIMA',null,'0023','150118',null,null,null);
Insert into COSORIO.EMPLEADOR (COD_EMPLEADOR,RAZ_EMPLEADOR,NOMCOM_EMPLEADOR,DIR_EMPLEADOR,REF_EMPLEADOR,DIS_EMPLEADOR,PRO_EMPLEADOR,DEP_EMPLEADOR,SEC_EMPLEADOR,SEG_EMPLEADOR,CON_EMPLEADOR,EST_EMPLEADOR,TEL_EMPLEADOR,FECINS_EMPLEADOR,FECINI_EMPLEADOR,FEC_EMPLEADOR,TIP_EMPLEADOR,REP_EMPLEADOR,EMP_EMPLEADOR,CARREP_EMPLEADOR,CONEMP_EMPLEADOR,TIPCON_EMPLEADOR,OFI_EMPLEADOR,SUBSECT_EMPLEADOR,FAX_EMPLEADOR,CIU_EMPLEADOR,SECCIU1_EMPLEADOR,SECCIU2_EMPLEADOR,AFE_EMPLEADOR,BUE_EMPLEADOR,AGERET_EMPLEADOR,AGEPER_EMPLEADOR,AGEPERC_EMPLEADOR,TIPODOC_EMPLEADOR,RUC_SECTOR,FECHA_MODIFICACION,REFAUX_EMPLEADOR,REFAUX2_EMPLEADOR,ESTREFER_EMPLEADOR,CODDEPEN_EMPLEADOR,CODUBIG_EMPLEADOR,TIPDOC_EMPLEADOR,NUMDOC_EMPLEADOR,CORREO_EMPLEADOR) values ('20181505365','Hospital Virgen del Carmen AIS','Hospital Virgen del Carmen AIS','AV. BOLIVAR N° S/N  PUEBLO LIBRE (MAGDALENA VIEJA) - LIMA - LIMA','CUADRA OCHO                             ','PUEBLO LIBRE (MAGDALENA VIEJA)','LIMA','LIMA','PUBLICO','SEGURO REGULAR','HABIDO','ACTIVO','- / - / -',to_date('24/08/1993','DD/MM/RRRR'),to_date('01/01/1950','DD/MM/RRRR'),to_date('06/02/2024','DD/MM/RRRR'),'INSTITUCIONES PUBLICAS','NALVARTE TAMBINI RAUL',null,'DIRECTOR',null,'INSTITUCIONES PUBLICAS',null,'ENTIDAD ESTADO',null,'ACTIVIDADES DE HOSPITALES',null,null,null,null,null,null,null,'RUC',null,to_date('06/02/2024','DD/MM/RRRR'),'CUADRA OCHO','AV. BOLIVAR N° S/N  PUEBLO LIBRE (MAGDALENA VIEJA) - LIMA - LIMA',null,'0021','150121',null,null,null);
Insert into COSORIO.EMPLEADOR (COD_EMPLEADOR,RAZ_EMPLEADOR,NOMCOM_EMPLEADOR,DIR_EMPLEADOR,REF_EMPLEADOR,DIS_EMPLEADOR,PRO_EMPLEADOR,DEP_EMPLEADOR,SEC_EMPLEADOR,SEG_EMPLEADOR,CON_EMPLEADOR,EST_EMPLEADOR,TEL_EMPLEADOR,FECINS_EMPLEADOR,FECINI_EMPLEADOR,FEC_EMPLEADOR,TIP_EMPLEADOR,REP_EMPLEADOR,EMP_EMPLEADOR,CARREP_EMPLEADOR,CONEMP_EMPLEADOR,TIPCON_EMPLEADOR,OFI_EMPLEADOR,SUBSECT_EMPLEADOR,FAX_EMPLEADOR,CIU_EMPLEADOR,SECCIU1_EMPLEADOR,SECCIU2_EMPLEADOR,AFE_EMPLEADOR,BUE_EMPLEADOR,AGERET_EMPLEADOR,AGEPER_EMPLEADOR,AGEPERC_EMPLEADOR,TIPODOC_EMPLEADOR,RUC_SECTOR,FECHA_MODIFICACION,REFAUX_EMPLEADOR,REFAUX2_EMPLEADOR,ESTREFER_EMPLEADOR,CODDEPEN_EMPLEADOR,CODUBIG_EMPLEADOR,TIPDOC_EMPLEADOR,NUMDOC_EMPLEADOR,CORREO_EMPLEADOR) values ('20374924251','Unidad de Administración Educativa Local 05','-','AV. ALVAREZ CALDERON CD.4 N° S/N C.H. TORRES DE LIMATAMBO  SAN BORJA - LIMA - LIMA','-','SAN BORJA','LIMA','LIMA','PUBLICO','SEGURO REGULAR','HABIDO','ACTIVO',null,to_date('21/10/1996','DD/MM/RRRR'),to_date('21/10/1996','DD/MM/RRRR'),to_date('08/10/2016','DD/MM/RRRR'),'UNIVERS. CENTROS EDUCAT. Y CULT.','SALDAÑA USCO GLORIA MARIA',null,'DIRECTOR',null,'UNIVERS. CENTROS EDUCAT. Y CULT.',null,'ENTIDAD ESTADO',null,'REGULACION DE ACTIVID.ORGANISMOS',null,null,null,null,null,null,null,'RUC',null,to_date('10/01/2024','DD/MM/RRRR'),'AV. ALVAREZ CALDERON CD.4 NRO. S/N C.H. TORRES DE LIMATAMBO - SAN BORJA - LIMA - LIMA ','AV. ALVAREZ CALDERON CD.4 N° S/N C.H. TORRES DE LIMATAMBO  SAN BORJA - LIMA - LIMA','1','0023','150130',null,null,null);
Insert into COSORIO.EMPLEADOR (COD_EMPLEADOR,RAZ_EMPLEADOR,NOMCOM_EMPLEADOR,DIR_EMPLEADOR,REF_EMPLEADOR,DIS_EMPLEADOR,PRO_EMPLEADOR,DEP_EMPLEADOR,SEC_EMPLEADOR,SEG_EMPLEADOR,CON_EMPLEADOR,EST_EMPLEADOR,TEL_EMPLEADOR,FECINS_EMPLEADOR,FECINI_EMPLEADOR,FEC_EMPLEADOR,TIP_EMPLEADOR,REP_EMPLEADOR,EMP_EMPLEADOR,CARREP_EMPLEADOR,CONEMP_EMPLEADOR,TIPCON_EMPLEADOR,OFI_EMPLEADOR,SUBSECT_EMPLEADOR,FAX_EMPLEADOR,CIU_EMPLEADOR,SECCIU1_EMPLEADOR,SECCIU2_EMPLEADOR,AFE_EMPLEADOR,BUE_EMPLEADOR,AGERET_EMPLEADOR,AGEPER_EMPLEADOR,AGEPERC_EMPLEADOR,TIPODOC_EMPLEADOR,RUC_SECTOR,FECHA_MODIFICACION,REFAUX_EMPLEADOR,REFAUX2_EMPLEADOR,ESTREFER_EMPLEADOR,CODDEPEN_EMPLEADOR,CODUBIG_EMPLEADOR,TIPDOC_EMPLEADOR,NUMDOC_EMPLEADOR,CORREO_EMPLEADOR) values ('20542605584','Protecsui S.A.C.','SUISEGUR','CAL. PUERTO ESPAÑA N° 240 URB. SANTA PATRICIA  LA MOLINA - LIMA - LIMA','-','LA MOLINA','LIMA','LIMA','PRIVADO','SEGURO REGULAR','HABIDO','ACTIVO','- / - / -',to_date('07/08/2001','DD/MM/RRRR'),to_date('07/08/2001','DD/MM/RRRR'),to_date('31/10/2019','DD/MM/RRRR'),'SOCIEDAD ANONIMA CERRADA','TELLO ALIAGA CARLOS ALBERTO',null,'GERENTE GENERAL',null,'SOCIEDAD ANONIMA CERRADA',null,null,null,'ACTIV. DE INVESTIGACION Y SEGURIDAD.',null,null,null,null,null,null,null,'RUC',null,to_date('10/01/2024','DD/MM/RRRR'),null,'CAL. PUERTO ESPAÑA N° 240 URB. SANTA PATRICIA  LA MOLINA - LIMA - LIMA',null,'0021','150114',null,null,null);
Insert into COSORIO.EMPLEADOR (COD_EMPLEADOR,RAZ_EMPLEADOR,NOMCOM_EMPLEADOR,DIR_EMPLEADOR,REF_EMPLEADOR,DIS_EMPLEADOR,PRO_EMPLEADOR,DEP_EMPLEADOR,SEC_EMPLEADOR,SEG_EMPLEADOR,CON_EMPLEADOR,EST_EMPLEADOR,TEL_EMPLEADOR,FECINS_EMPLEADOR,FECINI_EMPLEADOR,FEC_EMPLEADOR,TIP_EMPLEADOR,REP_EMPLEADOR,EMP_EMPLEADOR,CARREP_EMPLEADOR,CONEMP_EMPLEADOR,TIPCON_EMPLEADOR,OFI_EMPLEADOR,SUBSECT_EMPLEADOR,FAX_EMPLEADOR,CIU_EMPLEADOR,SECCIU1_EMPLEADOR,SECCIU2_EMPLEADOR,AFE_EMPLEADOR,BUE_EMPLEADOR,AGERET_EMPLEADOR,AGEPER_EMPLEADOR,AGEPERC_EMPLEADOR,TIPODOC_EMPLEADOR,RUC_SECTOR,FECHA_MODIFICACION,REFAUX_EMPLEADOR,REFAUX2_EMPLEADOR,ESTREFER_EMPLEADOR,CODDEPEN_EMPLEADOR,CODUBIG_EMPLEADOR,TIPDOC_EMPLEADOR,NUMDOC_EMPLEADOR,CORREO_EMPLEADOR) values ('20497905462','Dirección Nacional de Servicio Público',null,'PJ. FRANCISCO DE ZELA N° 150  JESUS MARIA - LIMA - LIMA','MINISTERIO DE TRABAJO PISO 10','JESUS MARIA','LIMA','LIMA','PUBLICO',null,'HABIDO','ACTIVO','- / - / -',to_date('11/11/2008','DD/MM/RRRR'),to_date('11/11/2008','DD/MM/RRRR'),to_date('09/05/2023','DD/MM/RRRR'),'INSTITUCIONES PUBLICAS','CORONEL OLANO NORVIL',null,'JEFE',null,'INSTITUCIONES PUBLICAS',null,null,null,'ACTIV. ADMINIST. PUBLICA EN GENERAL',null,null,null,null,null,null,null,'RUC',null,to_date('07/06/2023','DD/MM/RRRR'),null,'PJ. FRANCISCO DE ZELA N° 150  JESUS MARIA - LIMA - LIMA',null,'0021','150113',null,null,null);
Insert into COSORIO.EMPLEADOR (COD_EMPLEADOR,RAZ_EMPLEADOR,NOMCOM_EMPLEADOR,DIR_EMPLEADOR,REF_EMPLEADOR,DIS_EMPLEADOR,PRO_EMPLEADOR,DEP_EMPLEADOR,SEC_EMPLEADOR,SEG_EMPLEADOR,CON_EMPLEADOR,EST_EMPLEADOR,TEL_EMPLEADOR,FECINS_EMPLEADOR,FECINI_EMPLEADOR,FEC_EMPLEADOR,TIP_EMPLEADOR,REP_EMPLEADOR,EMP_EMPLEADOR,CARREP_EMPLEADOR,CONEMP_EMPLEADOR,TIPCON_EMPLEADOR,OFI_EMPLEADOR,SUBSECT_EMPLEADOR,FAX_EMPLEADOR,CIU_EMPLEADOR,SECCIU1_EMPLEADOR,SECCIU2_EMPLEADOR,AFE_EMPLEADOR,BUE_EMPLEADOR,AGERET_EMPLEADOR,AGEPER_EMPLEADOR,AGEPERC_EMPLEADOR,TIPODOC_EMPLEADOR,RUC_SECTOR,FECHA_MODIFICACION,REFAUX_EMPLEADOR,REFAUX2_EMPLEADOR,ESTREFER_EMPLEADOR,CODDEPEN_EMPLEADOR,CODUBIG_EMPLEADOR,TIPDOC_EMPLEADOR,NUMDOC_EMPLEADOR,CORREO_EMPLEADOR) values ('20615067338','Corporación Kronos Perú S.A.C.','-','AV. PROLONGACION CHILLON LT. 50B OTR. CHACRA CERRO SAN PEDRO  COMAS - LIMA - LIMA','-','COMAS','LIMA','LIMA','PRIVADO',null,'HABIDO','ACTIVO','- / - / -',to_date('16/12/2011','DD/MM/RRRR'),to_date('16/12/2011','DD/MM/RRRR'),to_date('22/08/2024','DD/MM/RRRR'),'SOCIEDAD ANONIMA CERRADA','CONTRERAS VILLANUEVA FELIPE',null,'GERENTE GENERAL',null,'SOCIEDAD ANONIMA CERRADA',null,null,null,'FAB. DE PINTURAS Y BARNICES.','FAB. DE OTROS PROD. QUIMICOS NEOP.',null,null,null,null,null,null,'RUC',null,to_date('25/09/2024','DD/MM/RRRR'),null,'AV. PISTA LENTA MZ. E-6 LT. 14-A URB. PRO INDUSTRIAL  SAN MARTIN DE PORRES - LIMA - LIMA',null,'0021','150110',null,null,null);
Insert into COSORIO.EMPLEADOR (COD_EMPLEADOR,RAZ_EMPLEADOR,NOMCOM_EMPLEADOR,DIR_EMPLEADOR,REF_EMPLEADOR,DIS_EMPLEADOR,PRO_EMPLEADOR,DEP_EMPLEADOR,SEC_EMPLEADOR,SEG_EMPLEADOR,CON_EMPLEADOR,EST_EMPLEADOR,TEL_EMPLEADOR,FECINS_EMPLEADOR,FECINI_EMPLEADOR,FEC_EMPLEADOR,TIP_EMPLEADOR,REP_EMPLEADOR,EMP_EMPLEADOR,CARREP_EMPLEADOR,CONEMP_EMPLEADOR,TIPCON_EMPLEADOR,OFI_EMPLEADOR,SUBSECT_EMPLEADOR,FAX_EMPLEADOR,CIU_EMPLEADOR,SECCIU1_EMPLEADOR,SECCIU2_EMPLEADOR,AFE_EMPLEADOR,BUE_EMPLEADOR,AGERET_EMPLEADOR,AGEPER_EMPLEADOR,AGEPERC_EMPLEADOR,TIPODOC_EMPLEADOR,RUC_SECTOR,FECHA_MODIFICACION,REFAUX_EMPLEADOR,REFAUX2_EMPLEADOR,ESTREFER_EMPLEADOR,CODDEPEN_EMPLEADOR,CODUBIG_EMPLEADOR,TIPDOC_EMPLEADOR,NUMDOC_EMPLEADOR,CORREO_EMPLEADOR) values ('20314256147','Hilos y Afines Eduardo EIRL','-','AV. ANGELICA GAMARRA DE LEON MZ. A LT. 15 URB. EL TREBOL 4TA ETPA  LOS OLIVOS - LIMA - LIMA','ALT 6TA CDR AV A. GAMARRA','LOS OLIVOS','LIMA','LIMA','PRIVADO',null,'HABIDO','SUSPENSION TEMPORAL','- / - / -',to_date('12/10/2006','DD/MM/RRRR'),to_date('01/11/2006','DD/MM/RRRR'),to_date('14/01/2025','DD/MM/RRRR'),'EMPRESA INDIVIDUAL DE RESP. LTDA','PAUCAR VELARDE WILFREDO ORLANDO',null,'GERENTE',null,'EMPRESA INDIVIDUAL DE RESP. LTDA',null,null,null,'PREP Y TEJ DE FIBRAS TEXTILES.',null,null,null,null,null,null,null,'RUC',null,to_date('14/01/2025','DD/MM/RRRR'),null,'AV. ANGELICA GAMARRA DE LEON MZ. A LT. 15 URB. EL TREBOL 4TA ETPA  LOS OLIVOS - LIMA - LIMA',null,'0023','150117',null,null,null);

--------------------------------------------------------
--  DDL for Index ACTUALIZAR_EMPLEADOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "COSORIO"."ACTUALIZAR_EMPLEADOR" ON "COSORIO"."EMPLEADOR" ("COD_EMPLEADOR", "FECHA_MODIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTAIND_INDEX" ;
--------------------------------------------------------
--  DDL for Index CODIGO_EMPLEADOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "COSORIO"."CODIGO_EMPLEADOR" ON "COSORIO"."EMPLEADOR" ("COD_EMPLEADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTAIND_INDEX" ;
--------------------------------------------------------
--  Constraints for Table EMPLEADOR
--------------------------------------------------------

  ALTER TABLE "COSORIO"."EMPLEADOR" ADD CONSTRAINT "CODIGO_EMPLEADOR" PRIMARY KEY ("COD_EMPLEADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTAIND_INDEX"  ENABLE;
  ALTER TABLE "COSORIO"."EMPLEADOR" MODIFY ("RAZ_EMPLEADOR" NOT NULL ENABLE);
  ALTER TABLE "COSORIO"."EMPLEADOR" MODIFY ("COD_EMPLEADOR" NOT NULL ENABLE);
