--------------------------------------------------------
-- Archivo creado  - viernes-abril-18-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESOLUTOR_G
--------------------------------------------------------

  CREATE TABLE "COSORIO"."RESOLUTOR_G" 
   (	"COD_RESOLUTOR" NUMBER(*,0), 
	"COD_APELACION" NUMBER(*,0), 
	"RESOLUTOR" VARCHAR2(200 BYTE), 
	"FECHA_ASIGNADO" DATE, 
	"FECHA_EMISION" DATE, 
	"FECHA_NOTIFICACION" DATE, 
	"RESOLUCION_APELACION" VARCHAR2(30 BYTE), 
	"FALLO" VARCHAR2(100 BYTE), 
	"MONTO_RESUELTO" NUMBER(38,2), 
	"ESTADO" VARCHAR2(100 BYTE), 
	"USUARIO_CREACION" VARCHAR2(50 BYTE), 
	"USUARIO_ACTUALIZACION" VARCHAR2(50 BYTE), 
	"FECHA_CREACION" DATE, 
	"FECHA_ACTUALIZACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTAIND_DATA" ;
REM INSERTING into COSORIO.RESOLUTOR_G
SET DEFINE OFF;
Insert into COSORIO.RESOLUTOR_G (COD_RESOLUTOR,COD_APELACION,RESOLUTOR,FECHA_ASIGNADO,FECHA_EMISION,FECHA_NOTIFICACION,RESOLUCION_APELACION,FALLO,MONTO_RESUELTO,ESTADO,USUARIO_CREACION,USUARIO_ACTUALIZACION,FECHA_CREACION,FECHA_ACTUALIZACION) values (114,114,'42538564',to_date('16/08/2024','DD/MM/RRRR'),to_date('30/09/2024','DD/MM/RRRR'),to_date('01/10/2024','DD/MM/RRRR'),'806150008124','FUNDADO',0,null,null,null,null,null);
Insert into COSORIO.RESOLUTOR_G (COD_RESOLUTOR,COD_APELACION,RESOLUTOR,FECHA_ASIGNADO,FECHA_EMISION,FECHA_NOTIFICACION,RESOLUCION_APELACION,FALLO,MONTO_RESUELTO,ESTADO,USUARIO_CREACION,USUARIO_ACTUALIZACION,FECHA_CREACION,FECHA_ACTUALIZACION) values (125,125,'42538564',to_date('19/09/2024','DD/MM/RRRR'),null,null,null,null,null,null,null,null,null,null);
Insert into COSORIO.RESOLUTOR_G (COD_RESOLUTOR,COD_APELACION,RESOLUTOR,FECHA_ASIGNADO,FECHA_EMISION,FECHA_NOTIFICACION,RESOLUCION_APELACION,FALLO,MONTO_RESUELTO,ESTADO,USUARIO_CREACION,USUARIO_ACTUALIZACION,FECHA_CREACION,FECHA_ACTUALIZACION) values (128,128,'42538564',to_date('20/09/2024','DD/MM/RRRR'),null,null,null,null,null,null,null,null,null,null);
Insert into COSORIO.RESOLUTOR_G (COD_RESOLUTOR,COD_APELACION,RESOLUTOR,FECHA_ASIGNADO,FECHA_EMISION,FECHA_NOTIFICACION,RESOLUCION_APELACION,FALLO,MONTO_RESUELTO,ESTADO,USUARIO_CREACION,USUARIO_ACTUALIZACION,FECHA_CREACION,FECHA_ACTUALIZACION) values (131,131,'25601936',to_date('19/09/2024','DD/MM/RRRR'),null,null,null,null,null,null,null,null,null,null);
Insert into COSORIO.RESOLUTOR_G (COD_RESOLUTOR,COD_APELACION,RESOLUTOR,FECHA_ASIGNADO,FECHA_EMISION,FECHA_NOTIFICACION,RESOLUCION_APELACION,FALLO,MONTO_RESUELTO,ESTADO,USUARIO_CREACION,USUARIO_ACTUALIZACION,FECHA_CREACION,FECHA_ACTUALIZACION) values (139,139,'10751651',to_date('24/09/2024','DD/MM/RRRR'),to_date('11/10/2024','DD/MM/RRRR'),null,'806150008176','IMPROCEDENTE',2070,'PENDIENTE DE NOTIFICAR',null,null,null,null);
Insert into COSORIO.RESOLUTOR_G (COD_RESOLUTOR,COD_APELACION,RESOLUTOR,FECHA_ASIGNADO,FECHA_EMISION,FECHA_NOTIFICACION,RESOLUCION_APELACION,FALLO,MONTO_RESUELTO,ESTADO,USUARIO_CREACION,USUARIO_ACTUALIZACION,FECHA_CREACION,FECHA_ACTUALIZACION) values (165,165,'10751651',to_date('17/10/2024','DD/MM/RRRR'),null,null,'CON PROYECTO DE  RESOLUCION','EXTEMPORÁNEO',1640,'REMITIDO A MARISA EL 21.10.2024',null,null,null,null);
Insert into COSORIO.RESOLUTOR_G (COD_RESOLUTOR,COD_APELACION,RESOLUTOR,FECHA_ASIGNADO,FECHA_EMISION,FECHA_NOTIFICACION,RESOLUCION_APELACION,FALLO,MONTO_RESUELTO,ESTADO,USUARIO_CREACION,USUARIO_ACTUALIZACION,FECHA_CREACION,FECHA_ACTUALIZACION) values (194,194,'10751651',to_date('02/12/2024','DD/MM/RRRR'),null,null,null,null,null,null,null,null,null,null);
Insert into COSORIO.RESOLUTOR_G (COD_RESOLUTOR,COD_APELACION,RESOLUTOR,FECHA_ASIGNADO,FECHA_EMISION,FECHA_NOTIFICACION,RESOLUCION_APELACION,FALLO,MONTO_RESUELTO,ESTADO,USUARIO_CREACION,USUARIO_ACTUALIZACION,FECHA_CREACION,FECHA_ACTUALIZACION) values (10,10,'25601936',to_date('16/02/2024','DD/MM/RRRR'),null,null,null,'DEVUELTO A LA SGCNT',null,'FINALIZADO',null,null,null,null);
Insert into COSORIO.RESOLUTOR_G (COD_RESOLUTOR,COD_APELACION,RESOLUTOR,FECHA_ASIGNADO,FECHA_EMISION,FECHA_NOTIFICACION,RESOLUCION_APELACION,FALLO,MONTO_RESUELTO,ESTADO,USUARIO_CREACION,USUARIO_ACTUALIZACION,FECHA_CREACION,FECHA_ACTUALIZACION) values (20,20,'25601936',to_date('01/04/2024','DD/MM/RRRR'),to_date('02/05/2024','DD/MM/RRRR'),to_date('13/05/2024','DD/MM/RRRR'),'806150007953','INFUNDADO ',6607,'FINALIZADO',null,null,null,null);
Insert into COSORIO.RESOLUTOR_G (COD_RESOLUTOR,COD_APELACION,RESOLUTOR,FECHA_ASIGNADO,FECHA_EMISION,FECHA_NOTIFICACION,RESOLUCION_APELACION,FALLO,MONTO_RESUELTO,ESTADO,USUARIO_CREACION,USUARIO_ACTUALIZACION,FECHA_CREACION,FECHA_ACTUALIZACION) values (22,22,'25601936',to_date('01/04/2024','DD/MM/RRRR'),null,null,null,'DEVUELTO REC. DE RECONSID.',null,'FINALIZADO',null,null,null,null);
Insert into COSORIO.RESOLUTOR_G (COD_RESOLUTOR,COD_APELACION,RESOLUTOR,FECHA_ASIGNADO,FECHA_EMISION,FECHA_NOTIFICACION,RESOLUCION_APELACION,FALLO,MONTO_RESUELTO,ESTADO,USUARIO_CREACION,USUARIO_ACTUALIZACION,FECHA_CREACION,FECHA_ACTUALIZACION) values (31,31,'10751651',to_date('04/04/2024','DD/MM/RRRR'),null,null,null,null,null,null,null,null,null,null);
Insert into COSORIO.RESOLUTOR_G (COD_RESOLUTOR,COD_APELACION,RESOLUTOR,FECHA_ASIGNADO,FECHA_EMISION,FECHA_NOTIFICACION,RESOLUCION_APELACION,FALLO,MONTO_RESUELTO,ESTADO,USUARIO_CREACION,USUARIO_ACTUALIZACION,FECHA_CREACION,FECHA_ACTUALIZACION) values (73,73,'10751651',to_date('09/05/2024','DD/MM/RRRR'),to_date('03/07/2024','DD/MM/RRRR'),to_date('05/07/2024','DD/MM/RRRR'),'806150008042','FUNDADO',0,'FINALIZADO',null,null,null,null);
--------------------------------------------------------
--  DDL for Trigger TRG_RESOLUTOR_G
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "COSORIO"."TRG_RESOLUTOR_G" 
BEFORE INSERT ON RESOLUTOR_G
FOR EACH ROW
BEGIN
   IF :NEW.COD_RESOLUTOR IS NULL THEN
      :NEW.COD_RESOLUTOR := SEQ_RESOLUTOR_G.NEXTVAL;
   END IF;
END;
/
ALTER TRIGGER "COSORIO"."TRG_RESOLUTOR_G" ENABLE;
